def findcomplement(str):
    str = str[::-1]
    tempstr = list(str)
    for i in range(0,len(str)):
        if str[i] == 'A':
            tempstr[i] = 'T'
        elif str[i] == 'T':
            tempstr[i] = 'A'
        elif str[i] == 'C':
            tempstr[i] = 'G'
        elif str[i] == 'G':
            tempstr[i] = 'C'
    return ''.join(tempstr)

print(findcomplement('TGAGGAACGCGGGCGAGGAGCCAATGTAACGATGCGACTTGGCGCAGGGAAAGCAGGTGCGACGTTGCTCTAGTCACTTCGAGGAGCCTAGTAGAGACCATCCTTTCAGTCCCGTATCCACTGAAAATGGTGGAGACGTAGCTAAACATGACTGAGGGAGGGCAATAAAGCTACTCAGCTGGCGGACATGCTCGTGGCCCCCACGGAGGCCTTTCGAGAGGCCCGCTTAGTACCTGGACTTACTTTTAACCATATATAGTGGGTTTACTATTGGAAGCGCAAAATATGAGTGGACAAAACGATTTTTCAAAACAAAAGTGGCCGTAGGATATCCCTGCCAGATTGTTGAGCGTAGATTTGCACACCGACGGAAGGGTGTTTCACACCTCACTCCTGAGGCAGAGGGAATAGATGCTTGAGTTTTCACCTAGAACTCCGTCTAGAACTACTCTCAGTGGCGACACAGAATCCTGATAGTTTTTAACAGCTAACGTTTACACTACGGAGCTAATATCGGTGGGGGACTGTGCCCCGGCCGGCGACCGCGGCGTTTCCCCAGTAAAGCCCACGGCATCCTGTGATATAAACCCATGGACACAATCATCTTATAGAGGAACGAGATCGTGAGTTAACAATTTCCAAGTTAAAGTCGAAGCTGTCTTTGACTGCAATATTGATCGAGGCAAGCGCAATAGCTCGCACGGGATACTTAAGAAGCAAAGGGTTTGGATGCTAGTCCCCATGACTTAGATATATCGCCAGGATTGATTCCGGTCGAGTTATAGCATTATTGATACCCCTGAACGTAGCCGGATGACCGGTTTTTAAAGGATCCGAG'))