amino_codon = {'A':4,'R':6,'N':2,'D':2,'C':2,'Q':2,'E':2,'G':4,'H':2,'I':3,'L':6,'K':2,'M':1,'F':2,'P':4,'S':6,'T':4,'W':1,'Y':2,'V':4}

def codon_freq(proteinString):
    numberofRNAs = 1;
    length = len(proteinString)
    i=0
    while(length !=0):
        numberofRNAs *= amino_codon[proteinString[i]]
        i+=1
        length-=1
    return (numberofRNAs*3)%1000000


inputString1 = 'MDCLDWSAFIDVCMYVDCAVSVLLIRYIEAYIFHGADASTNIHEKYGRQIQCEECIQCDTFECVWQHWKECEVVCIDRMPAMPQASFSALPAASFRED' \
              'GYCNVIVHVPQSPDGSIFADCSKRHFQDMYDQFNTFDMDQRTIQRITSGHFMSQHFFFYFLYAWRWCVPSFIDVSKSKYDVNIAVDSCIMFKNVMFSWQVF' \
              'TQSFWTTGMACCRVRRFSLVGDMEAQGIDFHWCHMHFMGWVRLMFGAINEHWPAAGSFQTHVMQAWINSEKAKMRLQALLDCASMSYPMMCNDRTTYFMMQALD' \
              'EMDLGEFETHPVIEHMKMLAPEIHMWDILIGWCPIGVGLNSSYGKSATIDSQLQYEDGNQKWSVVPAFNRLLKCACSAMQPTNGQPDGLTFLCNHHTQPTNHD' \
              'DWFPSMYSKIHRIERLALINKPGWWWATCCHADEKIFFAKLYYHWTFPNVAKVNKPKRMLIKSGWMRWLPFRCHSVAYCECQKMCQSSYTIDYAGTNMPYGMAEGC' \
              'QSYDMEHAKLVTDSFWFFWWWFQKQNSNFTMMNQRRMGKSYSIQYTNFNLDACGNYTTCDAHGDCALVGSKNWDDVTIGSRQWQKAINYYEFAMNLDAKIMMPVY' \
              'RSKHQCSPKCEMHWCSHTTKRAHSMIKSMQDWCNRWNIPIISMLCACSFLLTGTCRKKCYDFNLEIQRLKHDSVWSGPIEKNLTGVMRPYDVVPKCTFYEQNAGAG' \
              'LSKCIGDLVWGWIALDVSFHNTPNLYYVWPEWTDPPTQQWRHKHSPPPNEMHHTQIMMIIDMRMVHRDVYPECPCCKIETFTCSHESFCPQIYAPVEWMTVAVDSGCW' \
              'LQAKTSKMGVTWMRLLGVECCQMWKWPQYWNVVVGHTFNLHYHHYQKWIKCWQWEHITGEPYHYPWCEVNEIDSHGRANCGMVMICPTNIQFKNCHFQYQHFMHFQVNL' \
              'QPVMIYYVEVDDKSKLTTKIPLDDMLHKFDITNDPFANFDQILWRFYYPAFKLEEIH'
inputString = 'MHYFWTNINMDMESHNHKIMRCMRSVCGGRFQQKRTGDGTMTEAYNCVLECACTPRSVNCQTGVCHDIEEFKCRCMGVCMIDRLTGFECQAKKFCSVHYKVFRDLKFCQLAKGVTLKIWVVHQIMPSLLFQFLPENVMMYEICHAFSSHGIVDDFMPLSSCCNYILNYGNHKWVQVACGLWFIQLETYFTAPKTCTYNNFPYVQLTVHQNVTYEDMCKGSNCVKWNTYYNHARDNNVTMAVKPASDLAYWTKDVDDYAEIDFPYQCLNLNQLFEQSEAEFFEYNCEGRCSIHWFYYRRMTAMSFRGKCMNVVARWFIMCSEYAQAMRDAYTIQIMMHRNLAHKRTMQYMDFDQYINNENQPQRDDEETWRIWIHCSPRGLVVQLCQDLSTTMLCWCKVLTHDGCDLTWRYINQIVMYQWEWHVMKLQAVTEANDNMYYIKSCHMCQVITHEFKTIISEHKYHCNFPLKRKLEECCQTNGFVQTMHWKPWSTDCAQLLIMWKKSQMLVGNRDIKQCHRVYTSIHGSVNHFCCTVVVGIPLYGLSKWAAIPIEQSMAMPQFRQCVHWWASAWGMKGMRKYSKQPKLHYWDLGIQNHYCWRDIGAKWFLWLILFLEGCCIQNGKVDCCQNGENRMTWCQCFLYRGNVMSHLHRHEWCLARPPGADLQFPSVFVHKIKSYNEDTMGPPYRPSVNECQYGDIEIVMGMFQTSTHVCNLMCEKFWNWYNFVERSMDILQFVCKMVNKFQDSRQMCRAWTTKHQKPGRTTSENRIRWWGINHRVYCTCFSNERMSNLRWKKRFSFCQKVTDRPYCIKMTAHMSPWFHLPRNYNDVESGSEPVVLEFFATYRTSFMKLYNHHPIQHFLGMGGPKSLQRMGGSQINTKQLNLDGQQKHAGPCIFMQDEMHSNHQARNAKKWSVDHQINPWKSPCPDSSFKASFESSINKDVNYSYFVMHKFNFQQPEDCGGEHDMKQLIETLHANFIEGPAQCKREQMMRDCSDVCA'
print(codon_freq(inputString))